"""
    Admission API

    This API delivers data for the Admission project.  # noqa: E501

    The version of the OpenAPI document: 1.0.91
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import osis_admission_sdk
from osis_admission_sdk.model.general_education_proposition_dto_poste_diplomatique import GeneralEducationPropositionDTOPosteDiplomatique


class TestGeneralEducationPropositionDTOPosteDiplomatique(unittest.TestCase):
    """GeneralEducationPropositionDTOPosteDiplomatique unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testGeneralEducationPropositionDTOPosteDiplomatique(self):
        """Test GeneralEducationPropositionDTOPosteDiplomatique"""
        # FIXME: construct object with mandatory attributes with example values
        # model = GeneralEducationPropositionDTOPosteDiplomatique()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
