"""
    Admission API

    This API delivers data for the Admission project.  # noqa: E501

    The version of the OpenAPI document: 1.0.87
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import osis_admission_sdk
from osis_admission_sdk.model.proposition_search_doctorat import PropositionSearchDoctorat
globals()['PropositionSearchDoctorat'] = PropositionSearchDoctorat
from osis_admission_sdk.model.external_supervision_dto_proposition import ExternalSupervisionDTOProposition


class TestExternalSupervisionDTOProposition(unittest.TestCase):
    """ExternalSupervisionDTOProposition unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testExternalSupervisionDTOProposition(self):
        """Test ExternalSupervisionDTOProposition"""
        # FIXME: construct object with mandatory attributes with example values
        # model = ExternalSupervisionDTOProposition()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
