"""
    Admission API

    This API delivers data for the Admission project.  # noqa: E501

    The version of the OpenAPI document: 1.0.62
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import osis_admission_sdk
from osis_admission_sdk.model.curriculum_details_educationalexperienceyear_set import CurriculumDetailsEducationalexperienceyearSet
globals()['CurriculumDetailsEducationalexperienceyearSet'] = CurriculumDetailsEducationalexperienceyearSet
from osis_admission_sdk.model.curriculum_details_educational_experiences import CurriculumDetailsEducationalExperiences


class TestCurriculumDetailsEducationalExperiences(unittest.TestCase):
    """CurriculumDetailsEducationalExperiences unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testCurriculumDetailsEducationalExperiences(self):
        """Test CurriculumDetailsEducationalExperiences"""
        # FIXME: construct object with mandatory attributes with example values
        # model = CurriculumDetailsEducationalExperiences()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
