"""
    Admission API

    This API delivers data for the Admission project.  # noqa: E501

    The version of the OpenAPI document: 1.0.82
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import osis_admission_sdk
from osis_admission_sdk.model.choix_sexe import ChoixSexe


class TestChoixSexe(unittest.TestCase):
    """ChoixSexe unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testChoixSexe(self):
        """Test ChoixSexe"""
        # FIXME: construct object with mandatory attributes with example values
        # model = ChoixSexe()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
