"""
    Admission API

    This API delivers data for the Admission project.  # noqa: E501

    The version of the OpenAPI document: 1.0.92
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import osis_admission_sdk
from osis_admission_sdk.model.specifier_paiement_va_etre_ouvert_par_candidat_command import SpecifierPaiementVaEtreOuvertParCandidatCommand


class TestSpecifierPaiementVaEtreOuvertParCandidatCommand(unittest.TestCase):
    """SpecifierPaiementVaEtreOuvertParCandidatCommand unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testSpecifierPaiementVaEtreOuvertParCandidatCommand(self):
        """Test SpecifierPaiementVaEtreOuvertParCandidatCommand"""
        # FIXME: construct object with mandatory attributes with example values
        # model = SpecifierPaiementVaEtreOuvertParCandidatCommand()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
