"""
    Admission API

    This API delivers data for the Admission project.  # noqa: E501

    The version of the OpenAPI document: 1.0.47
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import osis_admission_sdk
from osis_admission_sdk.model.doctorate_proposition_dto_comptabilite import DoctoratePropositionDTOComptabilite


class TestDoctoratePropositionDTOComptabilite(unittest.TestCase):
    """DoctoratePropositionDTOComptabilite unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testDoctoratePropositionDTOComptabilite(self):
        """Test DoctoratePropositionDTOComptabilite"""
        # FIXME: construct object with mandatory attributes with example values
        # model = DoctoratePropositionDTOComptabilite()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
