"""
    Admission API

    This API delivers data for the Admission project.  # noqa: E501

    The version of the OpenAPI document: 1.0.51
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import osis_admission_sdk
from osis_admission_sdk.model.doctorate_proposition_dto_bourse_recherche import DoctoratePropositionDTOBourseRecherche
from osis_admission_sdk.model.doctorate_proposition_dto_comptabilite import DoctoratePropositionDTOComptabilite
from osis_admission_sdk.model.doctorate_proposition_dto_links import DoctoratePropositionDTOLinks
from osis_admission_sdk.model.inline_response200 import InlineResponse200
from osis_admission_sdk.model.proposition_search_doctorat import PropositionSearchDoctorat
globals()['DoctoratePropositionDTOBourseRecherche'] = DoctoratePropositionDTOBourseRecherche
globals()['DoctoratePropositionDTOComptabilite'] = DoctoratePropositionDTOComptabilite
globals()['DoctoratePropositionDTOLinks'] = DoctoratePropositionDTOLinks
globals()['InlineResponse200'] = InlineResponse200
globals()['PropositionSearchDoctorat'] = PropositionSearchDoctorat
from osis_admission_sdk.model.doctorate_proposition_dto import DoctoratePropositionDTO


class TestDoctoratePropositionDTO(unittest.TestCase):
    """DoctoratePropositionDTO unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testDoctoratePropositionDTO(self):
        """Test DoctoratePropositionDTO"""
        # FIXME: construct object with mandatory attributes with example values
        # model = DoctoratePropositionDTO()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
