"""
    Admission API

    This API delivers data for the Admission project.  # noqa: E501

    The version of the OpenAPI document: 1.0.56
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import osis_admission_sdk
from osis_admission_sdk.model.campus import Campus


class TestCampus(unittest.TestCase):
    """Campus unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testCampus(self):
        """Test Campus"""
        # FIXME: construct object with mandatory attributes with example values
        # model = Campus()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
