"""
    Admission API

    This API delivers data for the Admission project.  # noqa: E501

    The version of the OpenAPI document: 1.0.59
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import osis_admission_sdk
from osis_admission_sdk.model.civil_state import CivilState


class TestCivilState(unittest.TestCase):
    """CivilState unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testCivilState(self):
        """Test CivilState"""
        # FIXME: construct object with mandatory attributes with example values
        # model = CivilState()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
