"""
    Admission API

    This API delivers data for the Admission project.  # noqa: E501

    The version of the OpenAPI document: 1.0.45
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import osis_admission_sdk
from osis_admission_sdk.model.action_link import ActionLink
globals()['ActionLink'] = ActionLink
from osis_admission_sdk.model.general_education_proposition_dto_links import GeneralEducationPropositionDTOLinks


class TestGeneralEducationPropositionDTOLinks(unittest.TestCase):
    """GeneralEducationPropositionDTOLinks unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testGeneralEducationPropositionDTOLinks(self):
        """Test GeneralEducationPropositionDTOLinks"""
        # FIXME: construct object with mandatory attributes with example values
        # model = GeneralEducationPropositionDTOLinks()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
