"""
    Admission API

    This API delivers data for the Admission project.  # noqa: E501

    The version of the OpenAPI document: 1.0.81
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import osis_admission_sdk
from osis_admission_sdk.model.jury_identity_dto import JuryIdentityDTO


class TestJuryIdentityDTO(unittest.TestCase):
    """JuryIdentityDTO unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testJuryIdentityDTO(self):
        """Test JuryIdentityDTO"""
        # FIXME: construct object with mandatory attributes with example values
        # model = JuryIdentityDTO()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
