"""
    Admission API

    This API delivers data for the Admission project.  # noqa: E501

    The version of the OpenAPI document: 1.0.62
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import osis_admission_sdk
from osis_admission_sdk.model.general_education_completer_curriculum_command import GeneralEducationCompleterCurriculumCommand


class TestGeneralEducationCompleterCurriculumCommand(unittest.TestCase):
    """GeneralEducationCompleterCurriculumCommand unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testGeneralEducationCompleterCurriculumCommand(self):
        """Test GeneralEducationCompleterCurriculumCommand"""
        # FIXME: construct object with mandatory attributes with example values
        # model = GeneralEducationCompleterCurriculumCommand()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
