"""
    Admission API

    This API delivers data for the Admission project.  # noqa: E501

    The version of the OpenAPI document: 1.0.93
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import osis_admission_sdk
from osis_admission_sdk.model.diplomatic_post import DiplomaticPost


class TestDiplomaticPost(unittest.TestCase):
    """DiplomaticPost unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testDiplomaticPost(self):
        """Test DiplomaticPost"""
        # FIXME: construct object with mandatory attributes with example values
        # model = DiplomaticPost()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
