"""
    Admission API

    This API delivers data for the Admission project.  # noqa: E501

    The version of the OpenAPI document: 1.0.80
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import osis_admission_sdk
from osis_admission_sdk.model.activity_type import ActivityType
globals()['ActivityType'] = ActivityType
from osis_admission_sdk.model.curriculum_details_professional_experiences import CurriculumDetailsProfessionalExperiences


class TestCurriculumDetailsProfessionalExperiences(unittest.TestCase):
    """CurriculumDetailsProfessionalExperiences unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testCurriculumDetailsProfessionalExperiences(self):
        """Test CurriculumDetailsProfessionalExperiences"""
        # FIXME: construct object with mandatory attributes with example values
        # model = CurriculumDetailsProfessionalExperiences()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
