"""
    Admission API

    This API delivers data for the Admission project.  # noqa: E501

    The version of the OpenAPI document: 1.0.53
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import osis_admission_sdk
from osis_admission_sdk.model.action_link import ActionLink
globals()['ActionLink'] = ActionLink
from osis_admission_sdk.model.doctorate_dto_links import DoctorateDTOLinks


class TestDoctorateDTOLinks(unittest.TestCase):
    """DoctorateDTOLinks unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testDoctorateDTOLinks(self):
        """Test DoctorateDTOLinks"""
        # FIXME: construct object with mandatory attributes with example values
        # model = DoctorateDTOLinks()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
