"""
    Admission API

    This API delivers data for the Admission project.  # noqa: E501

    The version of the OpenAPI document: 1.0.36
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import osis_admission_sdk
from osis_admission_sdk.model.submit_confirmation_paper_command import SubmitConfirmationPaperCommand


class TestSubmitConfirmationPaperCommand(unittest.TestCase):
    """SubmitConfirmationPaperCommand unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testSubmitConfirmationPaperCommand(self):
        """Test SubmitConfirmationPaperCommand"""
        # FIXME: construct object with mandatory attributes with example values
        # model = SubmitConfirmationPaperCommand()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
