"""
    Admission API

    This API delivers data for the Admission project.  # noqa: E501

    The version of the OpenAPI document: 1.0.64
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import osis_admission_sdk
from osis_admission_sdk.model.contexte_formation import ContexteFormation


class TestContexteFormation(unittest.TestCase):
    """ContexteFormation unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testContexteFormation(self):
        """Test ContexteFormation"""
        # FIXME: construct object with mandatory attributes with example values
        # model = ContexteFormation()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
