"""
    Admission API

    This API delivers data for the Admission project.  # noqa: E501

    The version of the OpenAPI document: 1.0.70
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import osis_admission_sdk
from osis_admission_sdk.model.doctorate_proposition_dto_bourse_recherche import DoctoratePropositionDTOBourseRecherche


class TestDoctoratePropositionDTOBourseRecherche(unittest.TestCase):
    """DoctoratePropositionDTOBourseRecherche unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testDoctoratePropositionDTOBourseRecherche(self):
        """Test DoctoratePropositionDTOBourseRecherche"""
        # FIXME: construct object with mandatory attributes with example values
        # model = DoctoratePropositionDTOBourseRecherche()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
