"""
    Admission API

    This API delivers data for the Admission project.  # noqa: E501

    The version of the OpenAPI document: 1.0.42
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import osis_admission_sdk
from osis_admission_sdk.model.proposition_dto_comptabilite import PropositionDTOComptabilite


class TestPropositionDTOComptabilite(unittest.TestCase):
    """PropositionDTOComptabilite unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testPropositionDTOComptabilite(self):
        """Test PropositionDTOComptabilite"""
        # FIXME: construct object with mandatory attributes with example values
        # model = PropositionDTOComptabilite()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
