"""
    Admission API

    This API delivers data for the Admission project.  # noqa: E501

    The version of the OpenAPI document: 1.0.66
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import osis_admission_sdk
from osis_admission_sdk.model.high_school_diploma_high_school_diploma_alternative import HighSchoolDiplomaHighSchoolDiplomaAlternative


class TestHighSchoolDiplomaHighSchoolDiplomaAlternative(unittest.TestCase):
    """HighSchoolDiplomaHighSchoolDiplomaAlternative unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testHighSchoolDiplomaHighSchoolDiplomaAlternative(self):
        """Test HighSchoolDiplomaHighSchoolDiplomaAlternative"""
        # FIXME: construct object with mandatory attributes with example values
        # model = HighSchoolDiplomaHighSchoolDiplomaAlternative()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
