"""
    Admission API

    This API delivers data for the Admission project.  # noqa: E501

    The version of the OpenAPI document: 1.0.70
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import osis_admission_sdk
from osis_admission_sdk.model.action_link import ActionLink
globals()['ActionLink'] = ActionLink
from osis_admission_sdk.model.proposition_search_links3 import PropositionSearchLinks3


class TestPropositionSearchLinks3(unittest.TestCase):
    """PropositionSearchLinks3 unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testPropositionSearchLinks3(self):
        """Test PropositionSearchLinks3"""
        # FIXME: construct object with mandatory attributes with example values
        # model = PropositionSearchLinks3()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
