"""
    Admission API

    This API delivers data for the Admission project.  # noqa: E501

    The version of the OpenAPI document: 1.0.77
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import osis_admission_sdk
from osis_admission_sdk.model.renvoyer_invitation_signature_externe import RenvoyerInvitationSignatureExterne


class TestRenvoyerInvitationSignatureExterne(unittest.TestCase):
    """RenvoyerInvitationSignatureExterne unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testRenvoyerInvitationSignatureExterne(self):
        """Test RenvoyerInvitationSignatureExterne"""
        # FIXME: construct object with mandatory attributes with example values
        # model = RenvoyerInvitationSignatureExterne()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
