"""
    Admission API

    This API delivers data for the Admission project.  # noqa: E501

    The version of the OpenAPI document: 1.0.93
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import osis_admission_sdk
from osis_admission_sdk.model.pdf_recap import PDFRecap


class TestPDFRecap(unittest.TestCase):
    """PDFRecap unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testPDFRecap(self):
        """Test PDFRecap"""
        # FIXME: construct object with mandatory attributes with example values
        # model = PDFRecap()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
