"""
    Admission API

    This API delivers data for the Admission project.  # noqa: E501

    The version of the OpenAPI document: 1.0.5
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import osis_admission_sdk
from osis_admission_sdk.model.coordonnees_contact import CoordonneesContact


class TestCoordonneesContact(unittest.TestCase):
    """CoordonneesContact unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testCoordonneesContact(self):
        """Test CoordonneesContact"""
        # FIXME: construct object with mandatory attributes with example values
        # model = CoordonneesContact()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
