"""
    Admission API

    This API delivers data for the Admission project.  # noqa: E501

    The version of the OpenAPI document: 1.0.27
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import osis_admission_sdk
from osis_admission_sdk.model.submit_confirmation_paper_extension_request_command import SubmitConfirmationPaperExtensionRequestCommand


class TestSubmitConfirmationPaperExtensionRequestCommand(unittest.TestCase):
    """SubmitConfirmationPaperExtensionRequestCommand unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testSubmitConfirmationPaperExtensionRequestCommand(self):
        """Test SubmitConfirmationPaperExtensionRequestCommand"""
        # FIXME: construct object with mandatory attributes with example values
        # model = SubmitConfirmationPaperExtensionRequestCommand()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
