"""
    Admission API

    This API delivers data for the Admission project.  # noqa: E501

    The version of the OpenAPI document: 1.0.92
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import osis_admission_sdk
from osis_admission_sdk.model.identification_dto import IdentificationDTO


class TestIdentificationDTO(unittest.TestCase):
    """IdentificationDTO unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testIdentificationDTO(self):
        """Test IdentificationDTO"""
        # FIXME: construct object with mandatory attributes with example values
        # model = IdentificationDTO()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
