"""
    Admission API

    This API delivers data for the Admission project.  # noqa: E501

    The version of the OpenAPI document: 1.0.26
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import osis_admission_sdk
from osis_admission_sdk.model.study_system import StudySystem


class TestStudySystem(unittest.TestCase):
    """StudySystem unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testStudySystem(self):
        """Test StudySystem"""
        # FIXME: construct object with mandatory attributes with example values
        # model = StudySystem()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
