"""
    Admission API

    This API delivers data for the Admission project.  # noqa: E501

    The version of the OpenAPI document: 1.0.66
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import osis_admission_sdk
from osis_admission_sdk.model.modifier_questions_specifiques_formation_generale_command import ModifierQuestionsSpecifiquesFormationGeneraleCommand


class TestModifierQuestionsSpecifiquesFormationGeneraleCommand(unittest.TestCase):
    """ModifierQuestionsSpecifiquesFormationGeneraleCommand unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testModifierQuestionsSpecifiquesFormationGeneraleCommand(self):
        """Test ModifierQuestionsSpecifiquesFormationGeneraleCommand"""
        # FIXME: construct object with mandatory attributes with example values
        # model = ModifierQuestionsSpecifiquesFormationGeneraleCommand()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
