"""
    Admission API

    This API delivers data for the Admission project.  # noqa: E501

    The version of the OpenAPI document: 1.0.90
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import osis_admission_sdk
from osis_admission_sdk.model.ajouter_membre_command import AjouterMembreCommand


class TestAjouterMembreCommand(unittest.TestCase):
    """AjouterMembreCommand unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testAjouterMembreCommand(self):
        """Test AjouterMembreCommand"""
        # FIXME: construct object with mandatory attributes with example values
        # model = AjouterMembreCommand()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
