"""
    Admission API

    This API delivers data for the Admission project.  # noqa: E501

    The version of the OpenAPI document: 1.0.79
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import osis_admission_sdk
from osis_admission_sdk.model.confirmation_paper_dto_demande_prolongation import ConfirmationPaperDTODemandeProlongation


class TestConfirmationPaperDTODemandeProlongation(unittest.TestCase):
    """ConfirmationPaperDTODemandeProlongation unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testConfirmationPaperDTODemandeProlongation(self):
        """Test ConfirmationPaperDTODemandeProlongation"""
        # FIXME: construct object with mandatory attributes with example values
        # model = ConfirmationPaperDTODemandeProlongation()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
