"""
    Admission API

    This API delivers data for the Admission project.  # noqa: E501

    The version of the OpenAPI document: 1.0.91
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import osis_admission_sdk
from osis_admission_sdk.model.continuing_education_proposition_dto_adresse_facturation import ContinuingEducationPropositionDTOAdresseFacturation
from osis_admission_sdk.model.continuing_education_proposition_dto_links import ContinuingEducationPropositionDTOLinks
from osis_admission_sdk.model.inline_response200 import InlineResponse200
from osis_admission_sdk.model.proposition_search_formation import PropositionSearchFormation
globals()['ContinuingEducationPropositionDTOAdresseFacturation'] = ContinuingEducationPropositionDTOAdresseFacturation
globals()['ContinuingEducationPropositionDTOLinks'] = ContinuingEducationPropositionDTOLinks
globals()['InlineResponse200'] = InlineResponse200
globals()['PropositionSearchFormation'] = PropositionSearchFormation
from osis_admission_sdk.model.continuing_education_proposition_dto import ContinuingEducationPropositionDTO


class TestContinuingEducationPropositionDTO(unittest.TestCase):
    """ContinuingEducationPropositionDTO unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testContinuingEducationPropositionDTO(self):
        """Test ContinuingEducationPropositionDTO"""
        # FIXME: construct object with mandatory attributes with example values
        # model = ContinuingEducationPropositionDTO()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
