"""
    Admission API

    This API delivers data for the Admission project.  # noqa: E501

    The version of the OpenAPI document: 1.0.78
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import osis_admission_sdk
from osis_admission_sdk.model.completer_comptabilite_proposition_doctorale_command import CompleterComptabilitePropositionDoctoraleCommand


class TestCompleterComptabilitePropositionDoctoraleCommand(unittest.TestCase):
    """CompleterComptabilitePropositionDoctoraleCommand unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testCompleterComptabilitePropositionDoctoraleCommand(self):
        """Test CompleterComptabilitePropositionDoctoraleCommand"""
        # FIXME: construct object with mandatory attributes with example values
        # model = CompleterComptabilitePropositionDoctoraleCommand()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
