"""
    Admission API

    This API delivers data for the Admission project.  # noqa: E501

    The version of the OpenAPI document: 1.0.46
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import osis_admission_sdk
from osis_admission_sdk.model.accounting_conditions_last_french_community_high_education_institutes_attended import AccountingConditionsLastFrenchCommunityHighEducationInstitutesAttended


class TestAccountingConditionsLastFrenchCommunityHighEducationInstitutesAttended(unittest.TestCase):
    """AccountingConditionsLastFrenchCommunityHighEducationInstitutesAttended unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testAccountingConditionsLastFrenchCommunityHighEducationInstitutesAttended(self):
        """Test AccountingConditionsLastFrenchCommunityHighEducationInstitutesAttended"""
        # FIXME: construct object with mandatory attributes with example values
        # model = AccountingConditionsLastFrenchCommunityHighEducationInstitutesAttended()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
