"""
    Admission API

    This API delivers data for the Admission project.  # noqa: E501

    The version of the OpenAPI document: 1.0.84
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import osis_admission_sdk
from osis_admission_sdk.model.proposition_search_formation import PropositionSearchFormation


class TestPropositionSearchFormation(unittest.TestCase):
    """PropositionSearchFormation unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testPropositionSearchFormation(self):
        """Test PropositionSearchFormation"""
        # FIXME: construct object with mandatory attributes with example values
        # model = PropositionSearchFormation()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
