"""
    Admission API

    This API delivers data for the Admission project.  # noqa: E501

    The version of the OpenAPI document: 1.0.61
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import osis_admission_sdk
from osis_admission_sdk.model.modifier_choix_formation_continue_command import ModifierChoixFormationContinueCommand


class TestModifierChoixFormationContinueCommand(unittest.TestCase):
    """ModifierChoixFormationContinueCommand unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testModifierChoixFormationContinueCommand(self):
        """Test ModifierChoixFormationContinueCommand"""
        # FIXME: construct object with mandatory attributes with example values
        # model = ModifierChoixFormationContinueCommand()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
