"""
    Admission API

    This API delivers data for the Admission project.  # noqa: E501

    The version of the OpenAPI document: 1.0.83
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import osis_admission_sdk
from osis_admission_sdk.model.proposition_search_doctorat import PropositionSearchDoctorat


class TestPropositionSearchDoctorat(unittest.TestCase):
    """PropositionSearchDoctorat unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testPropositionSearchDoctorat(self):
        """Test PropositionSearchDoctorat"""
        # FIXME: construct object with mandatory attributes with example values
        # model = PropositionSearchDoctorat()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
