"""
    Admission API

    This API delivers data for the Admission project.  # noqa: E501

    The version of the OpenAPI document: 1.0.81
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import osis_admission_sdk
from osis_admission_sdk.model.continuing_education_proposition_dto_adresse_facturation import ContinuingEducationPropositionDTOAdresseFacturation


class TestContinuingEducationPropositionDTOAdresseFacturation(unittest.TestCase):
    """ContinuingEducationPropositionDTOAdresseFacturation unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testContinuingEducationPropositionDTOAdresseFacturation(self):
        """Test ContinuingEducationPropositionDTOAdresseFacturation"""
        # FIXME: construct object with mandatory attributes with example values
        # model = ContinuingEducationPropositionDTOAdresseFacturation()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
