"""
    Admission API

    This API delivers data for the Admission project.  # noqa: E501

    The version of the OpenAPI document: 1.0.74
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import osis_admission_sdk
from osis_admission_sdk.model.completer_comptabilite_proposition_generale_command import CompleterComptabilitePropositionGeneraleCommand


class TestCompleterComptabilitePropositionGeneraleCommand(unittest.TestCase):
    """CompleterComptabilitePropositionGeneraleCommand unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testCompleterComptabilitePropositionGeneraleCommand(self):
        """Test CompleterComptabilitePropositionGeneraleCommand"""
        # FIXME: construct object with mandatory attributes with example values
        # model = CompleterComptabilitePropositionGeneraleCommand()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
