"""
    Admission API

    This API delivers data for the Admission project.  # noqa: E501

    The version of the OpenAPI document: 1.0.73
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import osis_admission_sdk
from osis_admission_sdk.model.jury_dto_promoteurs import JuryDTOPromoteurs


class TestJuryDTOPromoteurs(unittest.TestCase):
    """JuryDTOPromoteurs unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testJuryDTOPromoteurs(self):
        """Test JuryDTOPromoteurs"""
        # FIXME: construct object with mandatory attributes with example values
        # model = JuryDTOPromoteurs()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
