"""
    Admission API

    This API delivers data for the Admission project.  # noqa: E501

    The version of the OpenAPI document: 1.0.31
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import osis_admission_sdk
from osis_admission_sdk.model.complete_confirmation_paper_by_promoter_command import CompleteConfirmationPaperByPromoterCommand


class TestCompleteConfirmationPaperByPromoterCommand(unittest.TestCase):
    """CompleteConfirmationPaperByPromoterCommand unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testCompleteConfirmationPaperByPromoterCommand(self):
        """Test CompleteConfirmationPaperByPromoterCommand"""
        # FIXME: construct object with mandatory attributes with example values
        # model = CompleteConfirmationPaperByPromoterCommand()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
