"""
    Admission API

    This API delivers data for the Admission project.  # noqa: E501

    The version of the OpenAPI document: 1.0.73
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import osis_admission_sdk
from osis_admission_sdk.model.formation_generale_dto import FormationGeneraleDTO


class TestFormationGeneraleDTO(unittest.TestCase):
    """FormationGeneraleDTO unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testFormationGeneraleDTO(self):
        """Test FormationGeneraleDTO"""
        # FIXME: construct object with mandatory attributes with example values
        # model = FormationGeneraleDTO()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
