"""
    Admission API

    This API delivers data for the Admission project.  # noqa: E501

    The version of the OpenAPI document: 1.0.39
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import osis_admission_sdk
from osis_admission_sdk.model.admission_type import AdmissionType


class TestAdmissionType(unittest.TestCase):
    """AdmissionType unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testAdmissionType(self):
        """Test AdmissionType"""
        # FIXME: construct object with mandatory attributes with example values
        # model = AdmissionType()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
