"""
    Admission API

    This API delivers data for the Admission project.  # noqa: E501

    The version of the OpenAPI document: 1.0.48
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import osis_admission_sdk
from osis_admission_sdk.model.curriculum_details_file import CurriculumDetailsFile


class TestCurriculumDetailsFile(unittest.TestCase):
    """CurriculumDetailsFile unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testCurriculumDetailsFile(self):
        """Test CurriculumDetailsFile"""
        # FIXME: construct object with mandatory attributes with example values
        # model = CurriculumDetailsFile()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
