"""
    Admission API

    This API delivers data for the Admission project.  # noqa: E501

    The version of the OpenAPI document: 1.0.0
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import osis_admission_sdk
from osis_admission_sdk.model.actor_type import ActorType
globals()['ActorType'] = ActorType
from osis_admission_sdk.model.add_supervision_actor import AddSupervisionActor


class TestAddSupervisionActor(unittest.TestCase):
    """AddSupervisionActor unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testAddSupervisionActor(self):
        """Test AddSupervisionActor"""
        # FIXME: construct object with mandatory attributes with example values
        # model = AddSupervisionActor()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
