"""
    Admission API

    This API delivers data for the Admission project.  # noqa: E501

    The version of the OpenAPI document: 1.0.48
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import osis_admission_sdk
from osis_admission_sdk.model.accounting_conditions_last_french_community_high_education_institutes_attended import AccountingConditionsLastFrenchCommunityHighEducationInstitutesAttended
globals()['AccountingConditionsLastFrenchCommunityHighEducationInstitutesAttended'] = AccountingConditionsLastFrenchCommunityHighEducationInstitutesAttended
from osis_admission_sdk.model.accounting_conditions import AccountingConditions


class TestAccountingConditions(unittest.TestCase):
    """AccountingConditions unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testAccountingConditions(self):
        """Test AccountingConditions"""
        # FIXME: construct object with mandatory attributes with example values
        # model = AccountingConditions()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
