"""
    Admission API

    This API delivers data for the Admission project.  # noqa: E501

    The version of the OpenAPI document: 1.0.83
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import osis_admission_sdk
from osis_admission_sdk.model.modifier_choix_formation_generale_command import ModifierChoixFormationGeneraleCommand


class TestModifierChoixFormationGeneraleCommand(unittest.TestCase):
    """ModifierChoixFormationGeneraleCommand unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testModifierChoixFormationGeneraleCommand(self):
        """Test ModifierChoixFormationGeneraleCommand"""
        # FIXME: construct object with mandatory attributes with example values
        # model = ModifierChoixFormationGeneraleCommand()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
