"""
    Admission API

    This API delivers data for the Admission project.  # noqa: E501

    The version of the OpenAPI document: 1.0.84
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import osis_admission_sdk
from osis_admission_sdk.model.choix_statut_proposition_generale import ChoixStatutPropositionGenerale
globals()['ChoixStatutPropositionGenerale'] = ChoixStatutPropositionGenerale
from osis_admission_sdk.model.general_education_proposition_identity_with_status import GeneralEducationPropositionIdentityWithStatus


class TestGeneralEducationPropositionIdentityWithStatus(unittest.TestCase):
    """GeneralEducationPropositionIdentityWithStatus unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testGeneralEducationPropositionIdentityWithStatus(self):
        """Test GeneralEducationPropositionIdentityWithStatus"""
        # FIXME: construct object with mandatory attributes with example values
        # model = GeneralEducationPropositionIdentityWithStatus()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
