"""
    Admission API

    This API delivers data for the Admission project.  # noqa: E501

    The version of the OpenAPI document: 1.0.44
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import osis_admission_sdk
from osis_admission_sdk.model.confirmation_paper_dto_demande_prolongation import ConfirmationPaperDTODemandeProlongation
globals()['ConfirmationPaperDTODemandeProlongation'] = ConfirmationPaperDTODemandeProlongation
from osis_admission_sdk.model.confirmation_paper_dto import ConfirmationPaperDTO


class TestConfirmationPaperDTO(unittest.TestCase):
    """ConfirmationPaperDTO unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testConfirmationPaperDTO(self):
        """Test ConfirmationPaperDTO"""
        # FIXME: construct object with mandatory attributes with example values
        # model = ConfirmationPaperDTO()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
