"""
    Admission API

    This API delivers data for the Admission project.  # noqa: E501

    The version of the OpenAPI document: 1.0.76
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import osis_admission_sdk
from osis_admission_sdk.model.actor_type import ActorType
globals()['ActorType'] = ActorType
from osis_admission_sdk.model.supervision_actor_reference import SupervisionActorReference


class TestSupervisionActorReference(unittest.TestCase):
    """SupervisionActorReference unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testSupervisionActorReference(self):
        """Test SupervisionActorReference"""
        # FIXME: construct object with mandatory attributes with example values
        # model = SupervisionActorReference()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
