"""
    Admission API

    This API delivers data for the Admission project.  # noqa: E501

    The version of the OpenAPI document: 1.0.81
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import osis_admission_sdk
from osis_admission_sdk.model.doctorate_education_accounting_dto_derniers_etablissements_superieurs_communaute_fr_frequentes import DoctorateEducationAccountingDTODerniersEtablissementsSuperieursCommunauteFrFrequentes
globals()['DoctorateEducationAccountingDTODerniersEtablissementsSuperieursCommunauteFrFrequentes'] = DoctorateEducationAccountingDTODerniersEtablissementsSuperieursCommunauteFrFrequentes
from osis_admission_sdk.model.doctorate_education_accounting_dto import DoctorateEducationAccountingDTO


class TestDoctorateEducationAccountingDTO(unittest.TestCase):
    """DoctorateEducationAccountingDTO unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testDoctorateEducationAccountingDTO(self):
        """Test DoctorateEducationAccountingDTO"""
        # FIXME: construct object with mandatory attributes with example values
        # model = DoctorateEducationAccountingDTO()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
