"""
    Admission API

    This API delivers data for the Admission project.  # noqa: E501

    The version of the OpenAPI document: 1.0.82
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import osis_admission_sdk
from osis_admission_sdk.model.actor_type import ActorType
globals()['ActorType'] = ActorType
from osis_admission_sdk.model.identifier_supervision_actor import IdentifierSupervisionActor


class TestIdentifierSupervisionActor(unittest.TestCase):
    """IdentifierSupervisionActor unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testIdentifierSupervisionActor(self):
        """Test IdentifierSupervisionActor"""
        # FIXME: construct object with mandatory attributes with example values
        # model = IdentifierSupervisionActor()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
