"""
    Admission API

    This API delivers data for the Admission project.  # noqa: E501

    The version of the OpenAPI document: 1.0.0
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import osis_admission_sdk
from osis_admission_sdk.model.person_detail import PersonDetail


class TestPersonDetail(unittest.TestCase):
    """PersonDetail unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testPersonDetail(self):
        """Test PersonDetail"""
        # FIXME: construct object with mandatory attributes with example values
        # model = PersonDetail()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
