"""
    Admission API

    This API delivers data for the Admission project.  # noqa: E501

    The version of the OpenAPI document: 1.0.68
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import osis_admission_sdk
from osis_admission_sdk.model.external_supervision_dto_proposition import ExternalSupervisionDTOProposition
from osis_admission_sdk.model.external_supervision_dto_supervision import ExternalSupervisionDTOSupervision
globals()['ExternalSupervisionDTOProposition'] = ExternalSupervisionDTOProposition
globals()['ExternalSupervisionDTOSupervision'] = ExternalSupervisionDTOSupervision
from osis_admission_sdk.model.external_supervision_dto import ExternalSupervisionDTO


class TestExternalSupervisionDTO(unittest.TestCase):
    """ExternalSupervisionDTO unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testExternalSupervisionDTO(self):
        """Test ExternalSupervisionDTO"""
        # FIXME: construct object with mandatory attributes with example values
        # model = ExternalSupervisionDTO()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
