"""
    Admission API

    This API delivers data for the Admission project.  # noqa: E501

    The version of the OpenAPI document: 1.0.85
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import osis_admission_sdk
from osis_admission_sdk.model.continuing_education_completer_curriculum_command import ContinuingEducationCompleterCurriculumCommand


class TestContinuingEducationCompleterCurriculumCommand(unittest.TestCase):
    """ContinuingEducationCompleterCurriculumCommand unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testContinuingEducationCompleterCurriculumCommand(self):
        """Test ContinuingEducationCompleterCurriculumCommand"""
        # FIXME: construct object with mandatory attributes with example values
        # model = ContinuingEducationCompleterCurriculumCommand()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
