"""
    Admission API

    This API delivers data for the Admission project.  # noqa: E501

    The version of the OpenAPI document: 1.0.78
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import osis_admission_sdk
from osis_admission_sdk.model.document_specific_question import DocumentSpecificQuestion


class TestDocumentSpecificQuestion(unittest.TestCase):
    """DocumentSpecificQuestion unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testDocumentSpecificQuestion(self):
        """Test DocumentSpecificQuestion"""
        # FIXME: construct object with mandatory attributes with example values
        # model = DocumentSpecificQuestion()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
