# coding: utf-8

"""

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    OpenAPI spec version: 1.0.0
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

import unittest

import osis_admission_sdk
from osis_admission_sdk.models.proposition_dto import PropositionDTO  # noqa: E501
from osis_admission_sdk.rest import ApiException


class TestPropositionDTO(unittest.TestCase):
    """PropositionDTO unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testPropositionDTO(self):
        """Test PropositionDTO"""
        # FIXME: construct object with mandatory attributes with example values
        # model = osis_admission_sdk.models.proposition_dto.PropositionDTO()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
