"""
    Admission API

    This API delivers data for the Admission project.  # noqa: E501

    The version of the OpenAPI document: 1.0.10
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import osis_admission_sdk
from osis_admission_sdk.model.supervision_dto_membre_ca import SupervisionDTOMembreCA


class TestSupervisionDTOMembreCA(unittest.TestCase):
    """SupervisionDTOMembreCA unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testSupervisionDTOMembreCA(self):
        """Test SupervisionDTOMembreCA"""
        # FIXME: construct object with mandatory attributes with example values
        # model = SupervisionDTOMembreCA()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
