"""
    Admission API

    This API delivers data for the Admission project.  # noqa: E501

    The version of the OpenAPI document: 1.0.56
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import osis_admission_sdk
from osis_admission_sdk.model.teaching_type_enum import TeachingTypeEnum


class TestTeachingTypeEnum(unittest.TestCase):
    """TeachingTypeEnum unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testTeachingTypeEnum(self):
        """Test TeachingTypeEnum"""
        # FIXME: construct object with mandatory attributes with example values
        # model = TeachingTypeEnum()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
