"""
    Admission API

    This API delivers data for the Admission project.  # noqa: E501

    The version of the OpenAPI document: 1.0.61
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import osis_admission_sdk
from osis_admission_sdk.model.continuing_education_accounting_dto import ContinuingEducationAccountingDTO


class TestContinuingEducationAccountingDTO(unittest.TestCase):
    """ContinuingEducationAccountingDTO unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testContinuingEducationAccountingDTO(self):
        """Test ContinuingEducationAccountingDTO"""
        # FIXME: construct object with mandatory attributes with example values
        # model = ContinuingEducationAccountingDTO()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
