"""
    Admission API

    This API delivers data for the Admission project.  # noqa: E501

    The version of the OpenAPI document: 1.0.64
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import osis_admission_sdk
from osis_admission_sdk.model.result import Result
globals()['Result'] = Result
from osis_admission_sdk.model.educational_experience_educationalexperienceyear_set import EducationalExperienceEducationalexperienceyearSet


class TestEducationalExperienceEducationalexperienceyearSet(unittest.TestCase):
    """EducationalExperienceEducationalexperienceyearSet unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testEducationalExperienceEducationalexperienceyearSet(self):
        """Test EducationalExperienceEducationalexperienceyearSet"""
        # FIXME: construct object with mandatory attributes with example values
        # model = EducationalExperienceEducationalexperienceyearSet()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
