"""
    Admission API

    This API delivers data for the Admission project.  # noqa: E501

    The version of the OpenAPI document: 1.0.58
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import osis_admission_sdk
from osis_admission_sdk.model.initier_proposition_continue_command import InitierPropositionContinueCommand


class TestInitierPropositionContinueCommand(unittest.TestCase):
    """InitierPropositionContinueCommand unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testInitierPropositionContinueCommand(self):
        """Test InitierPropositionContinueCommand"""
        # FIXME: construct object with mandatory attributes with example values
        # model = InitierPropositionContinueCommand()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
