"""
    Admission API

    This API delivers data for the Admission project.  # noqa: E501

    The version of the OpenAPI document: 1.0.51
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import osis_admission_sdk
from osis_admission_sdk.model.approuver_proposition_par_pdf_command import ApprouverPropositionParPdfCommand


class TestApprouverPropositionParPdfCommand(unittest.TestCase):
    """ApprouverPropositionParPdfCommand unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testApprouverPropositionParPdfCommand(self):
        """Test ApprouverPropositionParPdfCommand"""
        # FIXME: construct object with mandatory attributes with example values
        # model = ApprouverPropositionParPdfCommand()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
