"""
    Admission API

    This API delivers data for the Admission project.  # noqa: E501

    The version of the OpenAPI document: 1.0.81
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import osis_admission_sdk
from osis_admission_sdk.model.action_link import ActionLink
globals()['ActionLink'] = ActionLink
from osis_admission_sdk.model.continuing_education_proposition_dto_links import ContinuingEducationPropositionDTOLinks


class TestContinuingEducationPropositionDTOLinks(unittest.TestCase):
    """ContinuingEducationPropositionDTOLinks unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testContinuingEducationPropositionDTOLinks(self):
        """Test ContinuingEducationPropositionDTOLinks"""
        # FIXME: construct object with mandatory attributes with example values
        # model = ContinuingEducationPropositionDTOLinks()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
