"""
    Admission API

    This API delivers data for the Admission project.  # noqa: E501

    The version of the OpenAPI document: 1.0.77
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import osis_admission_sdk
from osis_admission_sdk.model.specific_question import SpecificQuestion


class TestSpecificQuestion(unittest.TestCase):
    """SpecificQuestion unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testSpecificQuestion(self):
        """Test SpecificQuestion"""
        # FIXME: construct object with mandatory attributes with example values
        # model = SpecificQuestion()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
