"""
    Admission API

    This API delivers data for the Admission project.  # noqa: E501

    The version of the OpenAPI document: 1.0.23
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import osis_admission_sdk
from osis_admission_sdk.model.foreign_study_cycle_type import ForeignStudyCycleType


class TestForeignStudyCycleType(unittest.TestCase):
    """ForeignStudyCycleType unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testForeignStudyCycleType(self):
        """Test ForeignStudyCycleType"""
        # FIXME: construct object with mandatory attributes with example values
        # model = ForeignStudyCycleType()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
