"""
    Admission API

    This API delivers data for the Admission project.  # noqa: E501

    The version of the OpenAPI document: 1.0.71
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import osis_admission_sdk
from osis_admission_sdk.model.doctorate_education_accounting_dto_derniers_etablissements_superieurs_communaute_fr_frequentes import DoctorateEducationAccountingDTODerniersEtablissementsSuperieursCommunauteFrFrequentes
globals()['DoctorateEducationAccountingDTODerniersEtablissementsSuperieursCommunauteFrFrequentes'] = DoctorateEducationAccountingDTODerniersEtablissementsSuperieursCommunauteFrFrequentes
from osis_admission_sdk.model.general_education_accounting_dto import GeneralEducationAccountingDTO


class TestGeneralEducationAccountingDTO(unittest.TestCase):
    """GeneralEducationAccountingDTO unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testGeneralEducationAccountingDTO(self):
        """Test GeneralEducationAccountingDTO"""
        # FIXME: construct object with mandatory attributes with example values
        # model = GeneralEducationAccountingDTO()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
