"""
    Admission API

    This API delivers data for the Admission project.  # noqa: E501

    The version of the OpenAPI document: 1.0.86
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import osis_admission_sdk
from osis_admission_sdk.model.payer_frais_dossier_proposition_suite_soumission_command import PayerFraisDossierPropositionSuiteSoumissionCommand


class TestPayerFraisDossierPropositionSuiteSoumissionCommand(unittest.TestCase):
    """PayerFraisDossierPropositionSuiteSoumissionCommand unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testPayerFraisDossierPropositionSuiteSoumissionCommand(self):
        """Test PayerFraisDossierPropositionSuiteSoumissionCommand"""
        # FIXME: construct object with mandatory attributes with example values
        # model = PayerFraisDossierPropositionSuiteSoumissionCommand()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
