"""
    Admission API

    This API delivers data for the Admission project.  # noqa: E501

    The version of the OpenAPI document: 1.0.67
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import osis_admission_sdk
from osis_admission_sdk.model.initier_proposition_generale_command import InitierPropositionGeneraleCommand


class TestInitierPropositionGeneraleCommand(unittest.TestCase):
    """InitierPropositionGeneraleCommand unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testInitierPropositionGeneraleCommand(self):
        """Test InitierPropositionGeneraleCommand"""
        # FIXME: construct object with mandatory attributes with example values
        # model = InitierPropositionGeneraleCommand()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
