"""
    Admission API

    This API delivers data for the Admission project.  # noqa: E501

    The version of the OpenAPI document: 1.0.93
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import osis_admission_sdk
from osis_admission_sdk.model.pool_questions import PoolQuestions


class TestPoolQuestions(unittest.TestCase):
    """PoolQuestions unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testPoolQuestions(self):
        """Test PoolQuestions"""
        # FIXME: construct object with mandatory attributes with example values
        # model = PoolQuestions()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
