"""
    Admission API

    This API delivers data for the Admission project.  # noqa: E501

    The version of the OpenAPI document: 1.0.57
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import osis_admission_sdk
from osis_admission_sdk.model.completer_comptabilite_proposition_continue_command import CompleterComptabilitePropositionContinueCommand


class TestCompleterComptabilitePropositionContinueCommand(unittest.TestCase):
    """CompleterComptabilitePropositionContinueCommand unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testCompleterComptabilitePropositionContinueCommand(self):
        """Test CompleterComptabilitePropositionContinueCommand"""
        # FIXME: construct object with mandatory attributes with example values
        # model = CompleterComptabilitePropositionContinueCommand()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
