"""
    Admission API

    This API delivers data for the Admission project.  # noqa: E501

    The version of the OpenAPI document: 1.0.73
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import osis_admission_sdk
from osis_admission_sdk.model.proposition_errors_elements_confirmation import PropositionErrorsElementsConfirmation


class TestPropositionErrorsElementsConfirmation(unittest.TestCase):
    """PropositionErrorsElementsConfirmation unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testPropositionErrorsElementsConfirmation(self):
        """Test PropositionErrorsElementsConfirmation"""
        # FIXME: construct object with mandatory attributes with example values
        # model = PropositionErrorsElementsConfirmation()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
