"""
    Admission API

    This API delivers data for the Admission project.  # noqa: E501

    The version of the OpenAPI document: 1.0.46
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import osis_admission_sdk
from osis_admission_sdk.model.designer_promoteur_reference_command import DesignerPromoteurReferenceCommand


class TestDesignerPromoteurReferenceCommand(unittest.TestCase):
    """DesignerPromoteurReferenceCommand unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testDesignerPromoteurReferenceCommand(self):
        """Test DesignerPromoteurReferenceCommand"""
        # FIXME: construct object with mandatory attributes with example values
        # model = DesignerPromoteurReferenceCommand()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
