"""
    Admission API

    This API delivers data for the Admission project.  # noqa: E501

    The version of the OpenAPI document: 1.0.35
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import osis_admission_sdk
from osis_admission_sdk.model.activity_sector import ActivitySector


class TestActivitySector(unittest.TestCase):
    """ActivitySector unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testActivitySector(self):
        """Test ActivitySector"""
        # FIXME: construct object with mandatory attributes with example values
        # model = ActivitySector()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
