"""
    Admission API

    This API delivers data for the Admission project.  # noqa: E501

    The version of the OpenAPI document: 1.0.65
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import osis_admission_sdk
from osis_admission_sdk.model.got_diploma import GotDiploma


class TestGotDiploma(unittest.TestCase):
    """GotDiploma unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testGotDiploma(self):
        """Test GotDiploma"""
        # FIXME: construct object with mandatory attributes with example values
        # model = GotDiploma()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
