"""
    Admission API

    This API delivers data for the Admission project.  # noqa: E501

    The version of the OpenAPI document: 1.0.52
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import osis_admission_sdk
from osis_admission_sdk.model.modifier_questions_specifiques_command import ModifierQuestionsSpecifiquesCommand


class TestModifierQuestionsSpecifiquesCommand(unittest.TestCase):
    """ModifierQuestionsSpecifiquesCommand unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testModifierQuestionsSpecifiquesCommand(self):
        """Test ModifierQuestionsSpecifiquesCommand"""
        # FIXME: construct object with mandatory attributes with example values
        # model = ModifierQuestionsSpecifiquesCommand()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
