"""
    Admission API

    This API delivers data for the Admission project.  # noqa: E501

    The version of the OpenAPI document: 1.0.87
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import osis_admission_sdk
from osis_admission_sdk.model.modifier_questions_specifiques_formation_continue_command import ModifierQuestionsSpecifiquesFormationContinueCommand


class TestModifierQuestionsSpecifiquesFormationContinueCommand(unittest.TestCase):
    """ModifierQuestionsSpecifiquesFormationContinueCommand unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testModifierQuestionsSpecifiquesFormationContinueCommand(self):
        """Test ModifierQuestionsSpecifiquesFormationContinueCommand"""
        # FIXME: construct object with mandatory attributes with example values
        # model = ModifierQuestionsSpecifiquesFormationContinueCommand()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
