"""
    Admission API

    This API delivers data for the Admission project.  # noqa: E501

    The version of the OpenAPI document: 1.0.0
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import osis_admission_sdk
from osis_admission_sdk.model.high_school_diploma_belgian_diploma_schedule import HighSchoolDiplomaBelgianDiplomaSchedule
globals()['HighSchoolDiplomaBelgianDiplomaSchedule'] = HighSchoolDiplomaBelgianDiplomaSchedule
from osis_admission_sdk.model.high_school_diploma_belgian_diploma import HighSchoolDiplomaBelgianDiploma


class TestHighSchoolDiplomaBelgianDiploma(unittest.TestCase):
    """HighSchoolDiplomaBelgianDiploma unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testHighSchoolDiplomaBelgianDiploma(self):
        """Test HighSchoolDiplomaBelgianDiploma"""
        # FIXME: construct object with mandatory attributes with example values
        # model = HighSchoolDiplomaBelgianDiploma()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
