"""
    Admission API

    This API delivers data for the Admission project.  # noqa: E501

    The version of the OpenAPI document: 1.0.52
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import osis_admission_sdk
from osis_admission_sdk.model.completer_comptabilite_proposition_command import CompleterComptabilitePropositionCommand


class TestCompleterComptabilitePropositionCommand(unittest.TestCase):
    """CompleterComptabilitePropositionCommand unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testCompleterComptabilitePropositionCommand(self):
        """Test CompleterComptabilitePropositionCommand"""
        # FIXME: construct object with mandatory attributes with example values
        # model = CompleterComptabilitePropositionCommand()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
