"""
    Admission API

    This API delivers data for the Admission project.  # noqa: E501

    The version of the OpenAPI document: 1.0.89
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import osis_admission_sdk
from osis_admission_sdk.model.membre_jury_dto import MembreJuryDTO


class TestMembreJuryDTO(unittest.TestCase):
    """MembreJuryDTO unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testMembreJuryDTO(self):
        """Test MembreJuryDTO"""
        # FIXME: construct object with mandatory attributes with example values
        # model = MembreJuryDTO()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
