"""
    Admission API

    This API delivers data for the Admission project.  # noqa: E501

    The version of the OpenAPI document: 1.0.87
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import osis_admission_sdk
from osis_admission_sdk.model.proposition_create_permissions_links import PropositionCreatePermissionsLinks
globals()['PropositionCreatePermissionsLinks'] = PropositionCreatePermissionsLinks
from osis_admission_sdk.model.proposition_create_permissions import PropositionCreatePermissions


class TestPropositionCreatePermissions(unittest.TestCase):
    """PropositionCreatePermissions unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testPropositionCreatePermissions(self):
        """Test PropositionCreatePermissions"""
        # FIXME: construct object with mandatory attributes with example values
        # model = PropositionCreatePermissions()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
