"""
    Admission API

    This API delivers data for the Admission project.  # noqa: E501

    The version of the OpenAPI document: 1.0.63
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import osis_admission_sdk
from osis_admission_sdk.model.proposition_search_formation import PropositionSearchFormation
from osis_admission_sdk.model.proposition_search_links2 import PropositionSearchLinks2
globals()['PropositionSearchFormation'] = PropositionSearchFormation
globals()['PropositionSearchLinks2'] = PropositionSearchLinks2
from osis_admission_sdk.model.proposition_search_continuing_education_propositions import PropositionSearchContinuingEducationPropositions


class TestPropositionSearchContinuingEducationPropositions(unittest.TestCase):
    """PropositionSearchContinuingEducationPropositions unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testPropositionSearchContinuingEducationPropositions(self):
        """Test PropositionSearchContinuingEducationPropositions"""
        # FIXME: construct object with mandatory attributes with example values
        # model = PropositionSearchContinuingEducationPropositions()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
