"""
    Admission API

    This API delivers data for the Admission project.  # noqa: E501

    The version of the OpenAPI document: 1.0.92
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import osis_admission_sdk
from osis_admission_sdk.model.action_link import ActionLink
globals()['ActionLink'] = ActionLink
from osis_admission_sdk.model.proposition_create_permissions_links import PropositionCreatePermissionsLinks


class TestPropositionCreatePermissionsLinks(unittest.TestCase):
    """PropositionCreatePermissionsLinks unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testPropositionCreatePermissionsLinks(self):
        """Test PropositionCreatePermissionsLinks"""
        # FIXME: construct object with mandatory attributes with example values
        # model = PropositionCreatePermissionsLinks()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
