"""
    Admission API

    This API delivers data for the Admission project.  # noqa: E501

    The version of the OpenAPI document: 1.0.92
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import osis_admission_sdk
from osis_admission_sdk.model.scholarship import Scholarship
globals()['Scholarship'] = Scholarship
from osis_admission_sdk.model.inline_response2004 import InlineResponse2004


class TestInlineResponse2004(unittest.TestCase):
    """InlineResponse2004 unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testInlineResponse2004(self):
        """Test InlineResponse2004"""
        # FIXME: construct object with mandatory attributes with example values
        # model = InlineResponse2004()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
