"""
    Admission API

    This API delivers data for the Admission project.  # noqa: E501

    The version of the OpenAPI document: 1.0.79
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import osis_admission_sdk
from osis_admission_sdk.model.supervision_dto_signatures_membres_ca import SupervisionDTOSignaturesMembresCA
from osis_admission_sdk.model.supervision_dto_signatures_promoteurs import SupervisionDTOSignaturesPromoteurs
globals()['SupervisionDTOSignaturesMembresCA'] = SupervisionDTOSignaturesMembresCA
globals()['SupervisionDTOSignaturesPromoteurs'] = SupervisionDTOSignaturesPromoteurs
from osis_admission_sdk.model.external_supervision_dto_supervision import ExternalSupervisionDTOSupervision


class TestExternalSupervisionDTOSupervision(unittest.TestCase):
    """ExternalSupervisionDTOSupervision unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testExternalSupervisionDTOSupervision(self):
        """Test ExternalSupervisionDTOSupervision"""
        # FIXME: construct object with mandatory attributes with example values
        # model = ExternalSupervisionDTOSupervision()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
