"""
    Admission API

    This API delivers data for the Admission project.  # noqa: E501

    The version of the OpenAPI document: 1.0.43
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import osis_admission_sdk
from osis_admission_sdk.model.proposition_search_doctorat import PropositionSearchDoctorat
from osis_admission_sdk.model.proposition_search_links1 import PropositionSearchLinks1
globals()['PropositionSearchDoctorat'] = PropositionSearchDoctorat
globals()['PropositionSearchLinks1'] = PropositionSearchLinks1
from osis_admission_sdk.model.proposition_search_doctorate_propositions import PropositionSearchDoctoratePropositions


class TestPropositionSearchDoctoratePropositions(unittest.TestCase):
    """PropositionSearchDoctoratePropositions unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testPropositionSearchDoctoratePropositions(self):
        """Test PropositionSearchDoctoratePropositions"""
        # FIXME: construct object with mandatory attributes with example values
        # model = PropositionSearchDoctoratePropositions()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
