"""
    Admission API

    This API delivers data for the Admission project.  # noqa: E501

    The version of the OpenAPI document: 1.0.58
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import osis_admission_sdk
from osis_admission_sdk.model.doctorate_identity_dto import DoctorateIdentityDTO


class TestDoctorateIdentityDTO(unittest.TestCase):
    """DoctorateIdentityDTO unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testDoctorateIdentityDTO(self):
        """Test DoctorateIdentityDTO"""
        # FIXME: construct object with mandatory attributes with example values
        # model = DoctorateIdentityDTO()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
