"""
    Admission API

    This API delivers data for the Admission project.  # noqa: E501

    The version of the OpenAPI document: 1.0.67
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import osis_admission_sdk
from osis_admission_sdk.model.supervision_dto_promoteur import SupervisionDTOPromoteur


class TestSupervisionDTOPromoteur(unittest.TestCase):
    """SupervisionDTOPromoteur unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testSupervisionDTOPromoteur(self):
        """Test SupervisionDTOPromoteur"""
        # FIXME: construct object with mandatory attributes with example values
        # model = SupervisionDTOPromoteur()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
