"""
    Admission API

    This API delivers data for the Admission project.  # noqa: E501

    The version of the OpenAPI document: 1.0.72
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import osis_admission_sdk
from osis_admission_sdk.model.proposition_errors_elements_confirmation import PropositionErrorsElementsConfirmation
from osis_admission_sdk.model.proposition_errors_errors import PropositionErrorsErrors
globals()['PropositionErrorsElementsConfirmation'] = PropositionErrorsElementsConfirmation
globals()['PropositionErrorsErrors'] = PropositionErrorsErrors
from osis_admission_sdk.model.proposition_errors import PropositionErrors


class TestPropositionErrors(unittest.TestCase):
    """PropositionErrors unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testPropositionErrors(self):
        """Test PropositionErrors"""
        # FIXME: construct object with mandatory attributes with example values
        # model = PropositionErrors()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
