"""
    Admission API

    This API delivers data for the Admission project.  # noqa: E501

    The version of the OpenAPI document: 1.0.50
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import osis_admission_sdk
from osis_admission_sdk.model.result import Result
globals()['Result'] = Result
from osis_admission_sdk.model.curriculum_details_educationalexperienceyear_set import CurriculumDetailsEducationalexperienceyearSet


class TestCurriculumDetailsEducationalexperienceyearSet(unittest.TestCase):
    """CurriculumDetailsEducationalexperienceyearSet unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testCurriculumDetailsEducationalexperienceyearSet(self):
        """Test CurriculumDetailsEducationalexperienceyearSet"""
        # FIXME: construct object with mandatory attributes with example values
        # model = CurriculumDetailsEducationalexperienceyearSet()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
