"""
    Admission API

    This API delivers data for the Admission project.  # noqa: E501

    The version of the OpenAPI document: 1.0.20
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import osis_admission_sdk
from osis_admission_sdk.model.action_link import ActionLink
globals()['ActionLink'] = ActionLink
from osis_admission_sdk.model.proposition_dto_links import PropositionDTOLinks


class TestPropositionDTOLinks(unittest.TestCase):
    """PropositionDTOLinks unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testPropositionDTOLinks(self):
        """Test PropositionDTOLinks"""
        # FIXME: construct object with mandatory attributes with example values
        # model = PropositionDTOLinks()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
