"""
    Admission API

    This API delivers data for the Admission project.  # noqa: E501

    The version of the OpenAPI document: 1.0.72
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import osis_admission_sdk
from osis_admission_sdk.model.statut_activite import StatutActivite


class TestStatutActivite(unittest.TestCase):
    """StatutActivite unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testStatutActivite(self):
        """Test StatutActivite"""
        # FIXME: construct object with mandatory attributes with example values
        # model = StatutActivite()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
