"""
    Admission API

    This API delivers data for the Admission project.  # noqa: E501

    The version of the OpenAPI document: 1.0.79
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import osis_admission_sdk
from osis_admission_sdk.model.completer_emplacements_documents_par_candidat_command import CompleterEmplacementsDocumentsParCandidatCommand


class TestCompleterEmplacementsDocumentsParCandidatCommand(unittest.TestCase):
    """CompleterEmplacementsDocumentsParCandidatCommand unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testCompleterEmplacementsDocumentsParCandidatCommand(self):
        """Test CompleterEmplacementsDocumentsParCandidatCommand"""
        # FIXME: construct object with mandatory attributes with example values
        # model = CompleterEmplacementsDocumentsParCandidatCommand()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
