"""
    Admission API

    This API delivers data for the Admission project.  # noqa: E501

    The version of the OpenAPI document: 1.0.13
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import osis_admission_sdk
from osis_admission_sdk.model.curriculum_file import CurriculumFile


class TestCurriculumFile(unittest.TestCase):
    """CurriculumFile unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testCurriculumFile(self):
        """Test CurriculumFile"""
        # FIXME: construct object with mandatory attributes with example values
        # model = CurriculumFile()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
