"""
    Admission API

    This API delivers data for the Admission project.  # noqa: E501

    The version of the OpenAPI document: 1.0.15
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import osis_admission_sdk
from osis_admission_sdk.model.experience_type import ExperienceType


class TestExperienceType(unittest.TestCase):
    """ExperienceType unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testExperienceType(self):
        """Test ExperienceType"""
        # FIXME: construct object with mandatory attributes with example values
        # model = ExperienceType()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
