"""
    Admission API

    This API delivers data for the Admission project.  # noqa: E501

    The version of the OpenAPI document: 1.0.84
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import osis_admission_sdk
from osis_admission_sdk.model.membre_jury_identity_dto import MembreJuryIdentityDTO


class TestMembreJuryIdentityDTO(unittest.TestCase):
    """MembreJuryIdentityDTO unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testMembreJuryIdentityDTO(self):
        """Test MembreJuryIdentityDTO"""
        # FIXME: construct object with mandatory attributes with example values
        # model = MembreJuryIdentityDTO()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
