"""
    Admission API

    This API delivers data for the Admission project.  # noqa: E501

    The version of the OpenAPI document: 1.0.47
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import osis_admission_sdk
from osis_admission_sdk.model.formation_continue_dto import FormationContinueDTO


class TestFormationContinueDTO(unittest.TestCase):
    """FormationContinueDTO unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testFormationContinueDTO(self):
        """Test FormationContinueDTO"""
        # FIXME: construct object with mandatory attributes with example values
        # model = FormationContinueDTO()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
