"""
    Admission API

    This API delivers data for the Admission project.  # noqa: E501

    The version of the OpenAPI document: 1.0.45
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import osis_admission_sdk
from osis_admission_sdk.model.doctorate_proposition_dto_bourse_erasmus_mundus import DoctoratePropositionDTOBourseErasmusMundus


class TestDoctoratePropositionDTOBourseErasmusMundus(unittest.TestCase):
    """DoctoratePropositionDTOBourseErasmusMundus unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testDoctoratePropositionDTOBourseErasmusMundus(self):
        """Test DoctoratePropositionDTOBourseErasmusMundus"""
        # FIXME: construct object with mandatory attributes with example values
        # model = DoctoratePropositionDTOBourseErasmusMundus()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
