"""
    Admission API

    This API delivers data for the Admission project.  # noqa: E501

    The version of the OpenAPI document: 1.0.87
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import osis_admission_sdk
from osis_admission_sdk.model.action_link import ActionLink
globals()['ActionLink'] = ActionLink
from osis_admission_sdk.model.proposition_search_links2 import PropositionSearchLinks2


class TestPropositionSearchLinks2(unittest.TestCase):
    """PropositionSearchLinks2 unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testPropositionSearchLinks2(self):
        """Test PropositionSearchLinks2"""
        # FIXME: construct object with mandatory attributes with example values
        # model = PropositionSearchLinks2()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
