"""
    Admission API

    This API delivers data for the Admission project.  # noqa: E501

    The version of the OpenAPI document: 1.0.92
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import osis_admission_sdk
from osis_admission_sdk.model.choix_genre import ChoixGenre


class TestChoixGenre(unittest.TestCase):
    """ChoixGenre unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testChoixGenre(self):
        """Test ChoixGenre"""
        # FIXME: construct object with mandatory attributes with example values
        # model = ChoixGenre()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
