"""
    Admission API

    This API delivers data for the Admission project.  # noqa: E501

    The version of the OpenAPI document: 1.0.93
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import osis_admission_sdk
from osis_admission_sdk.model.document_specific_questions_list_immediate_requested_documents import DocumentSpecificQuestionsListImmediateRequestedDocuments
globals()['DocumentSpecificQuestionsListImmediateRequestedDocuments'] = DocumentSpecificQuestionsListImmediateRequestedDocuments
from osis_admission_sdk.model.document_specific_questions_list import DocumentSpecificQuestionsList


class TestDocumentSpecificQuestionsList(unittest.TestCase):
    """DocumentSpecificQuestionsList unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testDocumentSpecificQuestionsList(self):
        """Test DocumentSpecificQuestionsList"""
        # FIXME: construct object with mandatory attributes with example values
        # model = DocumentSpecificQuestionsList()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
