"""
    Admission API

    This API delivers data for the Admission project.  # noqa: E501

    The version of the OpenAPI document: 1.0.60
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import osis_admission_sdk
from osis_admission_sdk.model.choix_doctorat_deja_realise import ChoixDoctoratDejaRealise


class TestChoixDoctoratDejaRealise(unittest.TestCase):
    """ChoixDoctoratDejaRealise unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testChoixDoctoratDejaRealise(self):
        """Test ChoixDoctoratDejaRealise"""
        # FIXME: construct object with mandatory attributes with example values
        # model = ChoixDoctoratDejaRealise()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
