"""
    Admission API

    This API delivers data for the Admission project.  # noqa: E501

    The version of the OpenAPI document: 1.0.37
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import osis_admission_sdk
from osis_admission_sdk.model.curriculum_educationalexperienceyear_set import CurriculumEducationalexperienceyearSet


class TestCurriculumEducationalexperienceyearSet(unittest.TestCase):
    """CurriculumEducationalexperienceyearSet unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testCurriculumEducationalexperienceyearSet(self):
        """Test CurriculumEducationalexperienceyearSet"""
        # FIXME: construct object with mandatory attributes with example values
        # model = CurriculumEducationalexperienceyearSet()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
