# coding: utf-8

# flake8: noqa
"""

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    OpenAPI spec version: 1.0.0
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

# import models into model package
from osis_admission_sdk.models.initier_proposition_command import InitierPropositionCommand
from osis_admission_sdk.models.proposition_dto import PropositionDTO
from osis_admission_sdk.models.proposition_identity_dto import PropositionIdentityDTO
