# flake8: noqa

"""
    Admission API

    This API delivers data for the Admission project.  # noqa: E501

    The version of the OpenAPI document: 1.0.11
    Generated by: https://openapi-generator.tech
"""


__version__ = "1.0.11"

# import ApiClient
from osis_admission_sdk.api_client import ApiClient

# import Configuration
from osis_admission_sdk.configuration import Configuration

# import exceptions
from osis_admission_sdk.exceptions import OpenApiException
from osis_admission_sdk.exceptions import ApiAttributeError
from osis_admission_sdk.exceptions import ApiTypeError
from osis_admission_sdk.exceptions import ApiValueError
from osis_admission_sdk.exceptions import ApiKeyError
from osis_admission_sdk.exceptions import ApiException
