# coding: utf-8

# flake8: noqa

"""

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    OpenAPI spec version: 1.0.0
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

__version__ = "1.0.0"

# import apis into sdk package
from osis_admission_sdk.api.propositions_api import PropositionsApi

# import ApiClient
from osis_admission_sdk.api_client import ApiClient
from osis_admission_sdk.configuration import Configuration
# import models into sdk package
from osis_admission_sdk.models.initier_proposition_command import InitierPropositionCommand
from osis_admission_sdk.models.proposition_dto import PropositionDTO
from osis_admission_sdk.models.proposition_identity_dto import PropositionIdentityDTO
